# Generated by Django 3.1.7 on 2021-03-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='city',
            field=models.TextField(default='Oslo'),
            preserve_default=False,
        ),
    ]
