# Generated by Django 3.1.7 on 2021-03-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacount', '0002_field_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='playerNames',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='player_name',
            field=models.TextField(null=True),
        ),
    ]
