# Generated by Django 3.1.7 on 2021-03-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacount', '0003_auto_20210313_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='pacount.game'),
            preserve_default=False,
        ),
    ]
